export const letras = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

export const temas = [
  "animais",
  "frutas",
  "cores",
  "países",
  "cidades",
  "nomes masculinos",
  "nomes femininos",
  "comidas",
  "bebidas",
  "flores",
  "profissões",
  "marcas",
  "esportes",
  "instrumentos musicais",
  "filmes",
  "séries de TV",
  "personagens de filmes",
  "personagens de desenhos animados",
  "livros",
  "autores",
  "músicas",
  "cantores",
  "bandas",
  "objetos",
  "partes do corpo",
  "vestuário",
  "calçados",
  "transportes",
  "elementos da natureza",
  "times de futebol",
  "jogos de videogame",
  "programas de TV",
  "festas e eventos",
  "plantas",
  "doces",
  "brinquedos",
  "super-heróis",
  "vilões",
  "mitologia",
  "ferramentas",
  "brincadeiras",
  "aplicativos",
  "websites",
  "tecnologias",
  "palavras em inglês",
  "palavras em espanhol",
  "palavras em francês",
  "pontos turísticos",
  "personagens históricos",
  "invenções",
  "ciências",
  "constelações",
  "planetas",
  "línguas",
  "emojis",
  "memes",
  "gêneros musicais",
  "estilos de dança",
  "revistas",
  "jornais",
  "bichos de estimação",
  "elementos químicos",
  "programas de computador",
  "distritos e bairros",
  "redes sociais",
  "movimentos artísticos",
  "estilos arquitetônicos",
  "prêmios",
  "teatros",
  "museus",
  "parques",
  "pontes",
  "praias",
  "ilhas",
  "rios",
  "montanhas",
  "monumentos",
  "obras de arte",
  "batalhas históricas",
  "símbolos nacionais",
  "tradições culturais",
  "culinárias típicas",
  "fatos científicos",
  "famosos",
  "palavras de quatro letras",
  "palavras de cinco letras",
  "animais marinhos",
  "animais extintos",
  "raças de cães",
  "raças de gatos",
  "espécies de aves",
  "personagens de livros",
  "idiomas fictícios",
  "escritores",
  "cientistas",
  "inventores",
  "pintores",
  "escultores",
  "celebridades",
  "políticos",
  "religiões",
  "festivais",
  "receitas culinárias",
];

export const splitIntoGroups = (array: any[], size: number) => {
  const result = [];

  for (let i = 0; i < array.length; i += size) {
    const chunk = array.slice(i, i + size);
    result.push(chunk);
  }

  return result;
};